-- TRIGGER --
	CREATE TRIGGER APELLIDO 
	ON HIJO FOR UPDATE 
	AS
	SET NOCOUNT ON
	DECLARE @HIJO_CODIGOPK int
	select @HIJO_CODIGOPK = HIJO_CODIGO  FROM INSERTED
	INSERT INTO NUEVO_APELLIDO VALUES(GETDATE(),@HIJO_CODIGOPK,
	'APELLIDO PATERNO ACTUALIZADO')
	GO
	UPDATE HIJO SET HIJO_APELLIDO = 'VELEZ ZAMBRANO' 
  	 for each row
              begin
             if :edad≥=18

	SELECT * FROM NUEVO_APELLIDO
	SELECT * FROM HIJO
